apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tavi-postgres-allow-api-worker
  namespace: tavi
spec:
  podSelector:
    matchLabels:
      app: tavi-postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: tavi-api
        - podSelector:
            matchLabels:
              app: tavi-worker
      ports:
        - protocol: TCP
          port: 5432
