version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - lifecycle
    ignore:
      - dependency-name: "@eslint/js"
        update-types:
          - version-update:semver-major
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - lifecycle
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /infra/docker
    schedule:
      interval: weekly
    labels:
      - dependencies
      - lifecycle
    groups:
      docker-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
