ALTER TABLE "Task"
ALTER COLUMN "assigneeUserId" DROP NOT NULL;

ALTER TABLE "Task"
DROP CONSTRAINT "Task_assigneeUserId_fkey";

ALTER TABLE "Task"
ADD CONSTRAINT "Task_assigneeUserId_fkey"
FOREIGN KEY ("assigneeUserId") REFERENCES "User"("id")
ON DELETE SET NULL
ON UPDATE CASCADE;
