apiVersion: v1
kind: ConfigMap
metadata:
  name: tavi-config
  namespace: tavi
data:
  API_PORT: "4000"
  WEB_PORT: "4173"
  WORKER_PORT: "4100"
  CORS_ORIGIN: "https://tavi.example.com"
  TAVI_HOME_URL: "https://tavi.example.com"
  VITE_API_BASE_URL: "https://tavi.example.com/api"
  SMTP_URL: "smtp://10.120.64.99:25"
  SMTP_FROM: "noreply@tavi.local"
