apiVersion: v1
kind: Secret
metadata:
  name: tavi-secrets
  namespace: tavi
type: Opaque
stringData:
  DATABASE_URL: "postgresql://username:password@postgres-host:5432/tavi?schema=public"
  COOKIE_SECRET: "replace-me"
