apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - backup-pvc.yaml
  - postgres-cluster.yaml
  - api-service.yaml
  - web-service.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - web-deployment.yaml
  - ingress.yaml
